# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Skin Sight' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
  pod 'SnapKit', '~> 5.0.0'
  pod 'Firebase/Analytics'
  pod 'Firebase/Auth'
  pod 'Firebase/Core'
  pod 'GoogleSignIn'
  pod 'FBSDKCoreKit'
  pod 'FBSDKLoginKit'
  # Pods for Skin Sight

  target 'Skin SightTests' do
    inherit! :search_paths
   pod 'SnapKit', '~> 5.0.0'
  end

  target 'Skin SightUITests' do
    pod 'SnapKit', '~> 5.0.0'
  end

end